export const oneTimeServices = {
    essential: {
      serviceName: "One-Time Essential Service",
      price: 129,
      requiredStaff: "1-2",
      sqftMin: 0,
      sqftMax: 1000,
      cleaningTime: "2-2.5 hours",
      services: [
        { id: "1", label: "General cleaning (vacuuming, dusting, trash removal)" },
        { id: "2", label: "Basic carpet maintenance" },
        { id: "3", label: "Restroom sanitization and restocking" },
        { id: "4", label: "Break room and kitchen cleaning" },
        { id: "5", label: "High-touch point disinfection" },
        { id: "6", label: "Spot cleaning of visible surfaces" },
        { id: "7", label: "Entry area maintenance" },
        { id: "8", label: "Interior window cleaning" },
      ],
    },
    core: {
      serviceName: "One-Time CoreCare Service",
      price: 359,
      requiredStaff: "2",
      sqftMin: 1001,
      sqftMax: 5000,
      cleaningTime: "2-2.5 hours",
      services: [
        { id: "1", label: "All essential service offerings" },
        { id: "2", label: "Deep carpet cleaning" },
        { id: "3", label: "Hard floor treatment" },
        { id: "4", label: "High dusting and vent cleaning" },
        { id: "5", label: "Enhanced disinfection protocols" },
        { id: "6", label: "Specialized surface treatment" },
        { id: "7", label: "Enhanced entryway maintenance" },
      ],
    },
  };
  
  export const monthlyServices = {
    monthlyEssential: {
      serviceName: "Essential Service",
      price: {
        2: 399,
        3: 499,
        5: 599,
      },
      requiredStaff: "1-2",
      sqftMin: 0,
      sqftMax: 1000,
      cleaningTime: "2-2.5 hours",
      services: [
        { id: "1", label: "General cleaning (vacuuming, dusting, trash removal)" },
        { id: "2", label: "Restroom sanitization and restocking" },
        { id: "3", label: "Break room and kitchen cleaning" },
        { id: "4", label: "Spot cleaning of visible surfaces" },
        { id: "5", label: "High-touch point disinfection" },
        { id: "6", label: "Entry area maintenance" },
      ],
    },
    monthlyCore: {
      serviceName: "CoreCare Service",
      price: {
        3: 1499,
        5: 2499,
        7: 3999,
      },
      requiredStaff: "1-2",
      sqftMin: 1001,
      sqftMax: 5000,
      cleaningTime: "2-2.5 hours",
      services: [
        { id: "1", label: "General cleaning (vacuuming, dusting, trash removal)" },
        { id: "2", label: "High-touch point disinfection" },
        { id: "3", label: "Restroom sanitization and restocking" },
        { id: "4", label: "Break room and kitchen cleaning" },
        { id: "5", label: "Maintaining a consistently clean and welcoming space" },
        { id: "6", label: "Spot cleaning of visible surfaces" },
        { id: "7", label: "Entry area maintenance" },
        { id: "8", label: "Focus on high-traffic areas" },
        { id: "9", label: "Thorough cleaning of all spaces" },
        { id: "10", label: "Provide cleaning supplies and equipment" },
      ],
    },
    monthlyProManage: {
      serviceName: "ProManage Service",
      price: {
        5: 3999,
        6: 5999,
        7: 7999,
      },
      requiredStaff: "2-3",
      sqftMin: 5001,
      sqftMax: 20000,
      cleaningTime: "7-8 hours",
      services: [
        { id: "1", label: "All CoreCare service offerings" },
        { id: "2", label: "Priority scheduling" },
        { id: "3", label: "Expanded coverage hours" },
        { id: "4", label: "More intensive floor care programs" },
        { id: "5", label: "Advanced disinfection protocols" },
        { id: "6", label: "Detailed attention to specialized surfaces" },
        { id: "7", label: "Frequent deep cleaning of high-traffic areas" },
        { id: "8", label: "Access to emergency response services" },
      ],
    },
    monthlyPeak: {
      serviceName: "Peak Performance Service",
      price: {
        6: 8999,
        7: 12999,
        24: 15999,
      },
      requiredStaff: "4-6",
      sqftMin: 200001,
      sqftMax: 1000000,
      cleaningTime: "10-12 hours",
      services: [
        { id: "1", label: "All ProManage service offerings" },
        { id: "2", label: "Highest standard of facility maintenance" },
        { id: "3", label: "Dedicated site supervision" },
        { id: "4", label: "Specialized cleaning protocols for different facility areas" },
        { id: "5", label: "Multi-shift coverage options" },
        { id: "6", label: "Advanced infection control measures" },
        { id: "7", label: "Comprehensive documentation of all services" },
        { id: "8", label: "Regular quality control inspections" },
        { id: "9", label: "Immediate response to facility issues" },
      ],
    },
  };
  